### ISSUE TITLE
esp32 sniffer is not very good ,please help me 

### ISSUE THREAD

**Issue by zhanglei-c** [lpodkalicki/blog#4]
Hi, When I use your code on esp32 ,it's work a moment,and will print this message 
"PACKET TYPE=DATA, CHAN=07, RSSI=-75, ADDR1=4c:74:bf:07:22:32, ADDR2=c8:3a:35:1d:6a:18, ADDR3=c8:3a:35:1d:6a:Task watchdog got triggered. The following tasks did not reset the watchdog in time:
 - IDLE (CPU 0)
Tasks currently running:
CPU 0: wifi
CPU 1: IDLE
18
PACKET TYPE=MGMT, CHAN=07, RSSI=-73, ADDR1=3c:e5:a6:f0:20:e0, ADDR2=c8:3a:35:1d:6a:18, ADDR3=c8:3a:35:1d:6a:18
"
but I not found any problem,please help me ,thank you very much

**Comment by lpodkalicki** [comment]
Still a problem or I can close?
